'use client'

/**
 * ParamAI Frontend — Copy Citations Component
 * Copy regulation citations to clipboard with formatting options
 *
 * Competition: AI Open Innovation Challenge 2026
 * Team: Group 1, President University
 */

import { useState } from 'react'
import { Copy, Check, FileText, List, Table2 } from 'lucide-react'
import { Parameter } from '@/lib/types'

interface CopyCitationsProps {
  parameters: Parameter[]
  productName?: string
  categoryCode?: string
  categoryName?: string
  confidence?: number
}

export default function CopyCitations({
  parameters,
  productName,
  categoryCode,
  categoryName,
  confidence,
}: CopyCitationsProps) {
  const [copiedFormat, setCopiedFormat] = useState<string | null>(null)
  const [showDropdown, setShowDropdown] = useState(false)

  const copyToClipboard = async (text: string, format: string) => {
    try {
      await navigator.clipboard.writeText(text)
      setCopiedFormat(format)
      setTimeout(() => setCopiedFormat(null), 2000)
    } catch (err) {
      console.error('Failed to copy:', err)
    }
  }

  // Format as plain text list
  const formatAsList = () => {
    let text = ''
    if (productName) text += `Product: ${productName}\n`
    if (categoryCode && categoryName) text += `Category: ${categoryCode} - ${categoryName}\n`
    if (confidence !== undefined) text += `Confidence: ${Math.round(confidence * 100)}%\n`
    text += '\nRequired Testing Parameters:\n'
    text += '─'.repeat(50) + '\n'

    parameters.forEach((param, index) => {
      text += `${index + 1}. ${param.name}\n`
      text += `   Standard: ${param.standard}\n`
      text += `   Regulation: ${param.regulation}\n`
      text += `   Type: ${param.type}\n\n`
    })

    text += '─'.repeat(50) + '\n'
    text += 'Generated by ParamAI - BPOM Testing Recommendation System\n'
    text += new Date().toLocaleString('en-US', {
      dateStyle: 'full',
      timeStyle: 'short'
    })

    return text
  }

  // Format as structured data (JSON-like)
  const formatAsStructured = () => {
    let text = 'BPOM TESTING PARAMETERS\n'
    text += '═'.repeat(50) + '\n\n'

    if (productName) text += `PRODUCT: ${productName.toUpperCase()}\n`
    if (categoryCode && categoryName) {
      text += `CATEGORY CODE: ${categoryCode}\n`
      text += `CATEGORY NAME: ${categoryName}\n`
    }
    if (confidence !== undefined) {
      text += `CONFIDENCE SCORE: ${Math.round(confidence * 100)}%\n`
      text += `REVIEW REQUIRED: ${confidence < 0.8 ? 'YES' : 'NO'}\n`
    }

    text += '\n' + '═'.repeat(50) + '\n'
    text += 'TESTING PARAMETERS\n'
    text += '─'.repeat(50) + '\n'

    // Group by type
    const grouped = parameters.reduce((acc, param) => {
      if (!acc[param.type]) acc[param.type] = []
      acc[param.type].push(param)
      return acc
    }, {} as Record<string, Parameter[]>)

    Object.entries(grouped).forEach(([type, params]) => {
      text += `\n[${type.toUpperCase().replace('_', ' ')}]\n`
      params.forEach((param, index) => {
        text += `  ${index + 1}. ${param.name}\n`
        text += `     └─ Standard: ${param.standard}\n`
        text += `     └─ Citation: ${param.regulation}\n`
      })
    })

    text += '\n' + '─'.repeat(50) + '\n'
    text += 'DISCLAIMER: This recommendation requires expert verification.\n'
    text += '─'.repeat(50) + '\n'
    text += `Generated: ${new Date().toISOString()}\n`
    text += 'System: ParamAI - AI-Powered BPOM Testing Recommendation\n'

    return text
  }

  // Format as Markdown table
  const formatAsMarkdown = () => {
    let md = ''
    if (productName) md += `**Product:** ${productName}\n`
    if (categoryCode && categoryName) md += `**Category:** ${categoryCode} - ${categoryName}\n`
    if (confidence !== undefined) md += `**Confidence:** ${Math.round(confidence * 100)}%\n`
    md += '\n## Required Testing Parameters\n\n'
    md += '| No | Parameter | Standard | Regulation | Type |\n'
    md += '|----|----------|---------|-----------|------|\n'
    parameters.forEach((param, index) => {
      md += `| ${index + 1} | ${param.name} | ${param.standard} | ${param.regulation} | ${param.type} |\n`
    })
    md += `\n---\n*Generated by ParamAI on ${new Date().toLocaleDateString()}*\n`
    return md
  }

  return (
    <div className="relative">
      {/* Dropdown Button */}
      <button
        onClick={() => setShowDropdown(!showDropdown)}
        className="flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium transition-all"
        style={{
          backgroundColor: '#eff6ff',
          color: '#1e40af',
          border: '1px solid #dbeafe',
        }}
        onMouseEnter={(e) => {
          e.currentTarget.style.backgroundColor = '#dbeafe'
        }}
        onMouseLeave={(e) => {
          e.currentTarget.style.backgroundColor = '#eff6ff'
        }}
      >
        {copiedFormat ? (
          <>
            <Check size={16} />
            <span>Copied!</span>
          </>
        ) : (
          <>
            <Copy size={16} />
            <span>Copy Citations</span>
          </>
        )}
      </button>

      {/* Dropdown Menu */}
      {showDropdown && (
        <>
          {/* Backdrop */}
          <div
            className="fixed inset-0 z-40"
            onClick={() => setShowDropdown(false)}
          />

          {/* Menu */}
          <div
            className="absolute right-0 mt-2 w-72 rounded-xl shadow-lg z-50 overflow-hidden"
            style={{
              backgroundColor: 'white',
              border: '1px solid #e5e7eb',
            }}
          >
            <div className="px-4 py-3" style={{ backgroundColor: '#f9fafb', borderBottom: '1px solid #e5e7eb' }}>
              <p className="text-sm font-semibold" style={{ color: '#1a1a2e' }}>Export Citations</p>
              <p className="text-xs" style={{ color: '#6b7280' }}>Choose format to copy</p>
            </div>

            <div className="py-2">
              {/* Plain Text */}
              <button
                onClick={() => {
                  copyToClipboard(formatAsList(), 'list')
                  setShowDropdown(false)
                }}
                className="w-full flex items-center gap-3 px-4 py-3 text-left transition-colors"
                style={{ backgroundColor: copiedFormat === 'list' ? '#eff6ff' : 'transparent' }}
                onMouseEnter={(e) => (e.currentTarget.style.backgroundColor = '#f9fafb')}
                onMouseLeave={(e) => (e.currentTarget.style.backgroundColor = copiedFormat === 'list' ? '#eff6ff' : 'transparent')}
              >
                <div
                  className="w-9 h-9 rounded-lg flex items-center justify-center"
                  style={{ backgroundColor: '#dbeafe' }}
                >
                  <List size={18} style={{ color: '#1e40af' }} />
                </div>
                <div className="flex-1">
                  <p className="text-sm font-semibold" style={{ color: '#1a1a2e' }}>Plain Text List</p>
                  <p className="text-xs" style={{ color: '#6b7280' }}>Simple readable format</p>
                </div>
                {copiedFormat === 'list' && <Check size={18} style={{ color: '#10b981' }} />}
              </button>

              {/* Structured Text */}
              <button
                onClick={() => {
                  copyToClipboard(formatAsStructured(), 'structured')
                  setShowDropdown(false)
                }}
                className="w-full flex items-center gap-3 px-4 py-3 text-left transition-colors"
                style={{ backgroundColor: copiedFormat === 'structured' ? '#eff6ff' : 'transparent' }}
                onMouseEnter={(e) => (e.currentTarget.style.backgroundColor = '#f9fafb')}
                onMouseLeave={(e) => (e.currentTarget.style.backgroundColor = copiedFormat === 'structured' ? '#eff6ff' : 'transparent')}
              >
                <div
                  className="w-9 h-9 rounded-lg flex items-center justify-center"
                  style={{ backgroundColor: '#fce7f3' }}
                >
                  <FileText size={18} style={{ color: '#9d174d' }} />
                </div>
                <div className="flex-1">
                  <p className="text-sm font-semibold" style={{ color: '#1a1a2e' }}>Structured Report</p>
                  <p className="text-xs" style={{ color: '#6b7280' }}>Professional format with grouping</p>
                </div>
                {copiedFormat === 'structured' && <Check size={18} style={{ color: '#10b981' }} />}
              </button>

              {/* Markdown Table */}
              <button
                onClick={() => {
                  copyToClipboard(formatAsMarkdown(), 'markdown')
                  setShowDropdown(false)
                }}
                className="w-full flex items-center gap-3 px-4 py-3 text-left transition-colors"
                style={{ backgroundColor: copiedFormat === 'markdown' ? '#eff6ff' : 'transparent' }}
                onMouseEnter={(e) => (e.currentTarget.style.backgroundColor = '#f9fafb')}
                onMouseLeave={(e) => (e.currentTarget.style.backgroundColor = copiedFormat === 'markdown' ? '#eff6ff' : 'transparent')}
              >
                <div
                  className="w-9 h-9 rounded-lg flex items-center justify-center"
                  style={{ backgroundColor: '#d1fae5' }}
                >
                  <Table2 size={18} style={{ color: '#065f46' }} />
                </div>
                <div className="flex-1">
                  <p className="text-sm font-semibold" style={{ color: '#1a1a2e' }}>Markdown Table</p>
                  <p className="text-xs" style={{ color: '#6b7280' }}>For documentation/wikis</p>
                </div>
                {copiedFormat === 'markdown' && <Check size={18} style={{ color: '#10b981' }} />}
              </button>
            </div>

            <div
              className="px-4 py-2 text-center"
              style={{ backgroundColor: '#f9fafb', borderTop: '1px solid #e5e7eb' }}
            >
              <p className="text-[10px]" style={{ color: '#9ca3af' }}>
                {parameters.length} parameters • {parameters.length * 3} citations total
              </p>
            </div>
          </div>
        </>
      )}
    </div>
  )
}